language: python

notifications:
  email: false
  
branches:
only:
  - master

install:
  - sudo apt-get -qq update
  - sudo apt-get install -y wget 
  - pip install -r requirements.txt 

before_script:
  - cd data 
  - ./download-data.sh
  - cd ..

script:
  - python -m unittest discover
  - cd plotting
  - python plot_phad_ablation.py
  - python plot_tuning.py
  - cd ..
  - python phad-c32.py
  - python phad_feat_all_but_one-c32.py
  - python phad_ttl_only.py
  - python gmm.py
  - python kdd_knn.py
  - ./check_results.py data/phad_results.csv data/master-listfile-condensed.txt --table 0.725 --thresh 0.725:0.725:1
